---
version: 2

updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    assignees:
      - jdno
    reviewers:
      - jdno
    labels:
      - C-dependency
      - L-github
      - R-ignore
